/* eslint no-unused-vars: 0 */

export const MIRI_EVENTS = {
  TOGGLE_EXTENSION: 'TOGGLE_EXTENSION',
  LOAD_SETTINGS: 'LOAD_SETTINGS',
  LOAD_FILTERS: 'LOAD_FILTERS',
  LOAD_SELECTORS: 'LOAD_SELECTORS',
  LOAD_EXTENSION_INFO: 'LOAD_EXTENSION_INFO',
  REQUEST_TOKEN: 'REQUEST_TOKEN',
  UPDATE_FURIGANA_SIZE: 'UPDATE_FURIGANA_SIZE',
  UPDATE_FURIGANA_COLOR: 'UPDATE_FURIGANA_COLOR',
  UPDATE_FURIGANA_SELECTABLE: 'UPDATE_FURIGANA_SELECTABLE',
  FILTER_ADDED: 'FILTER_ADDED',
  FILTER_DELETED: 'FILTER_DELETED',
  SELECTOR_ADDED: 'SELECTOR_ADDED',
  SELECTOR_DELETED: 'SELECTOR_DELETED',
  SETTING_CHANGED: 'SETTING_CHANGED',
  ACTIVATE_ELEMENT_PICKER: 'ACTIVATE_ELEMENT_PICKER',
  STORAGE_ACCESS: 'STORAGE_ACCESS'
};

export const PARSE_ENGINES = [
  {
    key: 'LOCAL_KUROMOJI',
    i18nKey: 'ui_engine_builtin',
  },
  {
    key: 'MIRIGANA_ONLINE',
    i18nKey: 'ui_engine_online',
  },
];

export const FURIGANA_COLORS = [
  {
    key: 'black',
    value: '#000',
  },
  {
    key: 'grey',
    value: '#6C7A89',
  },
  {
    key: 'blue',
    value: '#3498DB',
  },
  {
    key: 'purple',
    value: '#9B59B6',
  },
  {
    key: 'red',
    value: '#E74C3C',
  },
  {
    key: 'white',
    value: '#FFFFFF',
  },
];

export const STORAGE_KEYS = {
  EXTENSION_ENABLED_KEY: 'EXTENSION_ENABLED',
  FURIGANA_SIZE_PERCENTAGE_KEY: 'FURIGANA_SIZE_PERCENTAGE',
  FURIGANA_COLOR_KEY: 'FURIGANA_COLOR',
  FURIGANA_SELECTABLE_KEY: 'FURIGANA_SELECTABLE',
  FILTER_LIST_KEY: 'FILTER_LIST',
  SELECTORS_KEY: 'SELECTORS',
  TOKENS_KEY: 'TOKENS',
  CURRENT_PARSE_ENGINE_KEY: 'CURRENT_PARSE_ENGINE',
}

export const SETTING_DEFAULTS = {
  EXTENSION_ENABLED_DEFAULT: true,
  FURIGANA_SIZE_PERCENTAGE_DEFAULT: 50,
  FURIGANA_COLOR_DEFAULT: FURIGANA_COLORS[0].value,
  FURIGANA_SELECTABLE_DEFAULT: false,
  CURRENT_PARSE_ENGINE_DEFAULT: 'LOCAL_KUROMOJI',
}